-- Drop the legacy "Internal report" markdown column.
--   `report_markdown` was generated by the original writeReport() agent that
--   ran against the shallow pack only. It predates the merge + customer-report
--   pipeline. Nothing in production reads it any more (verified: no admin
--   route, no PDF export, no customer-facing view consumes it).

ALTER TABLE case_research_reports
  DROP COLUMN IF EXISTS report_markdown;
