import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Disclaimer",
  description:
    "CivilCase is not a law firm and does not provide legal advice. The information on this site is general legal information for non-lawyers and is not a substitute for an attorney.",
  alternates: { canonical: "/disclaimer" },
  openGraph: {
    title: "Disclaimer — CivilCase",
    description:
      "Important: CivilCase is not a law firm and does not provide legal advice.",
    url: "/disclaimer",
    type: "website",
  },
};

const jsonLd = {
  "@context": "https://schema.org",
  "@type": "WebPage",
  name: "Disclaimer",
  url: "https://civilcase.com/disclaimer",
  description:
    "Legal disclaimer for CivilCase users. CivilCase is not a law firm and does not provide legal advice.",
  publisher: {
    "@type": "Organization",
    name: "CivilCase",
    url: "https://civilcase.com",
  },
  inLanguage: "en-US",
};

export default function DisclaimerPage() {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />

      <section className="trust-hero">
        <div className="wrap-narrow">
          <div className="eyebrow">Disclaimer</div>
          <h1>
            Read this <em>before</em> you rely on anything we publish.
          </h1>
          <p className="trust-lede">
            CivilCase is a self-help legal-technology tool. We are not a law firm and we do
            not provide legal advice. The information on this site is general legal
            information and is not a substitute for the judgment of a licensed attorney
            considering the specific facts of your situation.
          </p>
        </div>
      </section>

      <section className="trust-section">
        <div className="wrap-narrow trust-content">
          <h2>1. Not a law firm</h2>
          <p className="trust-callout">
            CivilCase is owned and operated by a technology company, not a law firm. Using
            this site, signing up for an account, generating a demand letter, or
            corresponding with us does not create an attorney-client relationship. Nothing
            you tell us is protected by attorney-client privilege.
          </p>

          <h2>2. Not legal advice</h2>
          <p>
            The state guides, demand letter templates, and other content on CivilCase are
            general legal information presented for educational purposes. They are not
            tailored to your specific facts and do not account for the dozens of
            circumstances that can change how the law applies to your situation. If your
            case has any of the following, you should consult a licensed attorney in your
            state:
          </p>
          <ul className="trust-list">
            <li>Damages above your state&apos;s small-claims jurisdictional limit.</li>
            <li>Personal injury, defamation, or other tort claims.</li>
            <li>Disputes involving real property title, family law, or probate.</li>
            <li>Counterclaims that exceed the small-claims cap.</li>
            <li>Anything involving a federal claim, a government defendant, or arbitration clauses.</li>
            <li>Any case where you face criminal exposure or a regulatory complaint.</li>
          </ul>

          <h2>3. You are responsible for your own filings</h2>
          <p>
            Documents generated by CivilCase are produced from the information you provide.
            You are solely responsible for the accuracy and completeness of that
            information and for the legal sufficiency of any document you sign, send, or
            file with a court. Always read documents before signing or filing. Always
            verify deadlines, court addresses, and filing fees against the official court
            website before relying on them.
          </p>

          <h2>4. Information may be out of date</h2>
          <p>
            State laws, court rules, fees, and forms change frequently. We work hard to
            keep our guides current and we publish a <em>Last updated</em> date on every
            state page, but we cannot guarantee that every fact is current at the moment
            you read it. When timing matters, confirm with the official source.
          </p>

          <h2>5. No guarantee of outcome</h2>
          <p>
            CivilCase does not guarantee that you will win your case, recover money, or
            achieve any particular outcome. Whether your case succeeds depends on the
            facts, the evidence, the judge, and your own preparation, none of which we
            control. Past outcomes for other CivilCase users do not predict your result.
          </p>

          <h2>6. Limitation of liability</h2>
          <p>
            To the fullest extent permitted by law, CivilCase&apos;s liability arising from
            your use of this site is capped at the amount you paid us in the twelve months
            preceding the claim. CivilCase is not liable for indirect, incidental, or
            consequential damages, including lost recovery, lost time, or court costs you
            paid based on information you found here.
          </p>

          <h2>7. Use of AI</h2>
          <p>
            CivilCase uses AI to draft documents and research state laws. AI output is
            reviewed by humans before publication, but you should still read every document
            we generate before sending or filing it. AI can make mistakes, including
            citing statutes that don&apos;t apply to your case or omitting requirements
            that do. Read the document.
          </p>

          <h2>8. Consult an attorney when in doubt</h2>
          <p>
            CivilCase is built for the everyday disputes that don&apos;t justify hiring a
            lawyer. If you&apos;re unsure whether your case fits that description, the
            answer is probably to consult an attorney. Most state bars run a lawyer
            referral service that will connect you with a licensed attorney for a
            short, low-cost consultation.
          </p>

          <h2>9. Jurisdictional limitations</h2>
          <p>
            CivilCase is intended for use only by individuals and small businesses
            pursuing claims in U.S. small-claims, justice, or comparable trial-level
            courts in the fifty United States and the District of Columbia. We do not
            provide content for federal court litigation, tribal court matters,
            international disputes, or any matter outside the United States.
          </p>

          <h2>10. Contact</h2>
          <p>
            Questions about this disclaimer or our terms of use can be sent to{" "}
            <a href="mailto:legal@civilcase.com" className="trust-link">
              legal@civilcase.com
            </a>
            . By using CivilCase you acknowledge that you have read and understood this
            disclaimer.
          </p>
        </div>
      </section>

      <section className="trust-cta">
        <div className="wrap-narrow trust-cta-card">
          <h2>
            Still want to get <em>started</em>?
          </h2>
          <p>
            Most disputes are simple enough for a demand letter to resolve. Try ours.
          </p>
          <div className="hero-ctas">
            <Link className="btn btn-dark" href="/demand-letter">
              Send a Demand Letter
            </Link>
            <Link className="btn btn-cream" href="/about">
              About CivilCase
            </Link>
          </div>
        </div>
      </section>
    </>
  );
}
