import type { Metadata } from "next";
import Link from "next/link";
import { LegalDocLayout, type LegalSection } from "../../../components/firm";

export const metadata: Metadata = {
  title: "Disclaimer · CivilCase",
  description:
    "CivilCase is not a law firm and does not provide legal advice. The information on this site is general legal information for non-lawyers and is not a substitute for an attorney.",
  alternates: { canonical: "/disclaimer2" },
  robots: { index: false, follow: false },
};

const SECTIONS: LegalSection[] = [
  {
    id: "not-firm",
    title: "Not a law firm",
    body: (
      <p>
        CivilCase is owned and operated by a technology company, not a law firm. Using this site,
        signing up for an account, generating a demand letter, or corresponding with us does not
        create an attorney-client relationship. Nothing you tell us is protected by attorney-client
        privilege.
      </p>
    ),
  },
  {
    id: "not-advice",
    title: "Not legal advice",
    body: (
      <>
        <p>
          The state guides, demand letter templates, and other content on CivilCase are general legal
          information presented for educational purposes. They are not tailored to your facts and do
          not account for the dozens of circumstances that can change how the law applies to you.
          Consult a licensed attorney in your state if your case has any of the following:
        </p>
        <ul>
          <li>Damages above your state&rsquo;s small-claims jurisdictional limit.</li>
          <li>Personal injury, defamation, or other tort claims.</li>
          <li>Disputes involving real property title, family law, or probate.</li>
          <li>Counterclaims that exceed the small-claims cap.</li>
          <li>Anything involving a federal claim, a government defendant, or arbitration clauses.</li>
          <li>Any case where you face criminal exposure or a regulatory complaint.</li>
        </ul>
      </>
    ),
  },
  {
    id: "your-filings",
    title: "You are responsible for your own filings",
    body: (
      <p>
        Documents generated by CivilCase are produced from the information you provide. You are
        solely responsible for the accuracy and completeness of that information and for the legal
        sufficiency of any document you sign, send, or file with a court. Always read documents
        before signing or filing. Always verify deadlines, court addresses, and filing fees against
        the official court website before relying on them.
      </p>
    ),
  },
  {
    id: "out-of-date",
    title: "Information may be out of date",
    body: (
      <p>
        State laws, court rules, fees, and forms change frequently. We work hard to keep our guides
        current and we publish a Last updated date on every state page, but we cannot guarantee that
        every fact is current at the moment you read it. When timing matters, confirm with the
        official source.
      </p>
    ),
  },
  {
    id: "no-guarantee",
    title: "No guarantee of outcome",
    body: (
      <p>
        CivilCase does not guarantee that you will win your case, recover money, or achieve any
        particular outcome. Whether your case succeeds depends on the facts, the evidence, the
        judge, and your own preparation, none of which we control. Past outcomes for other CivilCase
        users do not predict your result.
      </p>
    ),
  },
  {
    id: "liability",
    title: "Limitation of liability",
    body: (
      <p>
        To the fullest extent permitted by law, CivilCase&rsquo;s liability arising from your use of
        this site is capped at the amount you paid us in the twelve months preceding the claim.
        CivilCase is not liable for indirect, incidental, or consequential damages, including lost
        recovery, lost time, or court costs you paid based on information you found here.
      </p>
    ),
  },
  {
    id: "ai",
    title: "Use of AI",
    body: (
      <p>
        CivilCase uses AI to draft documents and research state laws. AI output is reviewed by humans
        before publication, but you should still read every document we generate before sending or
        filing it. AI can make mistakes, including citing statutes that don&rsquo;t apply to your
        case or omitting requirements that do. Read the document.
      </p>
    ),
  },
  {
    id: "consult",
    title: "Consult an attorney when in doubt",
    body: (
      <p>
        CivilCase is built for the everyday disputes that don&rsquo;t justify hiring a lawyer. If
        you&rsquo;re unsure whether your case fits that description, the answer is probably to
        consult an attorney. Most state bars run a lawyer referral service that will connect you
        with a licensed attorney for a short, low-cost consultation.
      </p>
    ),
  },
  {
    id: "jurisdiction",
    title: "Jurisdictional limitations",
    body: (
      <p>
        CivilCase is intended for use only by individuals and small businesses pursuing claims in
        U.S. small-claims, justice, or comparable trial-level courts in the fifty United States and
        the District of Columbia. We do not provide content for federal court litigation, tribal
        court matters, international disputes, or any matter outside the United States.
      </p>
    ),
  },
  {
    id: "contact",
    title: "Contact",
    body: (
      <p>
        Questions about this disclaimer or our terms of use can be sent through our{" "}
        <Link href="/contact2">contact page</Link>. By using CivilCase you acknowledge that you have
        read and understood this disclaimer.
      </p>
    ),
  },
];

export default function Disclaimer2() {
  return (
    <LegalDocLayout
      eyebrowText="DISCLAIMER"
      title={<>Read this <em>before</em> you rely on anything we publish.</>}
      lede="CivilCase is a self-help legal-technology tool. We are not a law firm and we do not provide legal advice. The information on this site is general legal information and is not a substitute for the judgment of a licensed attorney considering the specific facts of your situation."
      badge={{
        label: "IMPORTANT",
        title: <>We are <em>not</em> a law firm.</>,
        body: "Owned and operated by a technology company. Using this site, signing up, or generating a demand letter does not create an attorney-client relationship. Nothing you tell us is privileged.",
      }}
      sections={SECTIONS}
    />
  );
}
